version: '3'

services:
  python:
    image: python
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD:-1234}"
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pghome:/home

volumes:
  pgdata: